<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Help
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">Comment trouver la définition d'un mot ?</span>
</p>

<p><b>Dans la page "Vocabulaire" :</b></p>

<ul>
  <li>Identifier le mot recherché dans la liste de vocabulaire, par exemple, ABATRE (en rouge)</li>
  <li>Repérer le numéro du tome, par exemple, II (en vert)</li>
  <li>Repérer le numéro de la page, par exemple, 198 (en vert)</li>
  <li>Repérer le numéro de la colonne, par exemple, II (en bleu)</li>
  <li>Repérer le numéro de la définition du mot, par exemple, n° 16 (en bleu)</li>
  <li>Entrer les numéros de tome et de page ci-dessus et cliquer sur "Afficher"</li>
</ul>

<img src="<?=$this->setLinkUrl('img/pages/lexrom-vocabulary-help.jpg');?>" />

<p><b>Dans la page "Consulter les définitions" :</b></p>

<ul>
  <li>Repérer, par exemple, le mot ABATTRE, dans la colonne II, définition n° 16, et lire la définition.</li>
  <li>Après avoir consulté la définition, il suffit de cliquer sur le lien "Vocabulaire" pour identifier un autre mot, et de répéter l'opération précédente pour consulter la définition de ce mot.</li>
</ul>

<img src="<?=$this->setLinkUrl('img/pages/lexrom-definition-help.jpg');?>" />
