<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Interface
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<div>

  <?php require "{$this->viewsDir}/interface/links.phtml";?>

  <a class="link"
     title="<?=$this->translate($this->dictionary['description']);?>"
    <?php if($this->dictionary['type'] != 'internal'):?>
      target="_blank"
      href="<?=$this->dictionary['introduction'];?>"
    <?php endif;?>
  ><?=$this->translate($this->dictionary['name']);?></a>

  <!-- copyright -->
  <span class="copyright-name">

   <span class="gray">
     <?=$this->translate('Powered by PHP');?>&nbsp;<?=PHP_VERSION;?>
     (<?=$this->displayTime((microtime(true) - $GLOBALS['_time']));?> s)
   </span>

    <a href="http://creativecommons.org/licenses/by-nc-nd/2.0/fr/" rel="license">
      <img class="middle" alt="Creative Commons License"
       style="border-width:0"
       src="http://i.creativecommons.org/l/by-nc-nd/2.0/fr/80x15.png" /></a>

    <span class="gray">2008-2013 Michel Corne</span>

  </span>

</div>