<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Interface
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<!-- links to pages: home, ... -->
<span class="item" >
  <a class="link" href="<?=$this->linksHelper->setHomeLink();?>"><?=$this->translate('Home');?></a>
  <a class="link" href="<?=$this->linksHelper->setIntroductionLink();?>"><?=$this->translate('Introduction');?></a>
  <a class="link options" href="<?=$this->linksHelper->setOptionsLink();?>"><?=$this->translate('Options');?></a>
  <a class="link" href="javascript:printPage()"><?=$this->translate('Print');?></a>
  <a class="link" href="<?=$this->linksHelper->setAboutLink();?>"><?=$this->translate('About');?></a>
  <a class="link" href="mailto:mcorne@yahoo.com?subject=Dicfro"><?=$this->translate('Contact');?></a>
  <?php if ($this->dictionary['type'] == 'external') :?>
      <a class="link" href="<?=$this->dictionary['introduction'];?>"><?=$this->translate('Direct link');?></a>
  <?php endif;?>
</span>
