<?php return array (
  0 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Search/JeanneauTest.php',
  1 => '/mnt/c/Data/netbeans/dicfro/tests/application/View/Helper/ImagesTest.php',
  2 => '/mnt/c/Data/netbeans/dicfro/tests/application/View/Helper/VerbsTest.php',
  3 => '/mnt/c/Data/netbeans/dicfro/tests/application/View/Helper/WordsTest.php',
  4 => '/mnt/c/Data/netbeans/dicfro/tests/application/Base/ViewTest.php',
  5 => '/mnt/c/Data/netbeans/dicfro/tests/application/Controller/FrontTest.php',
  6 => '/mnt/c/Data/netbeans/dicfro/tests/application/Base/ApplicationTest.php',
  7 => '/mnt/c/Data/netbeans/dicfro/tests/application/Controller/InterfaceTest.php',
  8 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/QueryTest.php',
  9 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Query/InternalTest.php',
  10 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Query/GhostwordsTest.php',
  11 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Query/TcafTest.php',
  12 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Query/ToblerTest.php',
  13 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Query/WhitakerTest.php',
  14 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Search/InternalTest.php',
  15 => '/mnt/c/Data/netbeans/dicfro/tests/application/Model/Search/TcafTest.php',
);