<?php return array (
  0 => 'D:\\Data\\dicfro\\tests/application/Base/StringTest.php',
  1 => 'D:\\Data\\dicfro\\tests/application/Model/Search/JeanneauTest.php',
  2 => 'D:\\Data\\dicfro\\tests/application/View/Helper/DictionariesTest.php',
  3 => 'D:\\Data\\dicfro\\tests/application/Model/QueryTest.php',
  4 => 'D:\\Data\\dicfro\\tests/application/Model/Query/WhitakerTest.php',
  5 => 'D:\\Data\\dicfro\\tests/application/Model/Query/ToblerTest.php',
  6 => 'D:\\Data\\dicfro\\tests/application/View/Helper/ImagesTest.php',
  7 => 'D:\\Data\\dicfro\\tests/application/Model/Query/TcafTest.php',
  8 => 'D:\\Data\\dicfro\\tests/application/Model/Search/TcafTest.php',
  9 => 'D:\\Data\\dicfro\\tests/application/View/Helper/VerbsTest.php',
  10 => 'D:\\Data\\dicfro\\tests/application/Model/Query/GenericTest.php',
  11 => 'D:\\Data\\dicfro\\tests/application/Model/Query/GhostwordsTest.php',
  12 => 'D:\\Data\\dicfro\\tests/application/View/Helper/WordsTest.php',
  13 => 'D:\\Data\\dicfro\\tests/application/Base/ViewTest.php',
  14 => 'D:\\Data\\dicfro\\tests/application/Model/Search/GenericTest.php',
  15 => 'D:\\Data\\dicfro\\tests/application/Controller/FrontTest.php',
  16 => 'D:\\Data\\dicfro\\tests/application/Controller/InterfaceTest.php',
  17 => 'D:\\Data\\dicfro\\tests/application/Base/ApplicationTest.php',
);