#!php
<?php
/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    Tests
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

require_once 'runtest.php';