<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">2 volumes - 1,500 pages - 70,000 entries</span>
</p>

<p>
The <a href="http://en.wikipedia.org/wiki/Century_Dictionary">Century Dictionary</a> supplement offers
“additional words, senses, and defined phrases representing the increase in scientific
and technological terminology, as well as in the common vocabulary,...
possessing a high degree of technical importance and general interest”.
</p>

<p class="sub-title">Links to the books at <a href="http://archive.org/">archive.org</a></p>
<ul>
  <li>Volume 11: <a href="http://archive.org/stream/cu31924091890685#page/n7/mode/2up">A - Littonioid</a></li>
  <li>Volume 12: <a href="http://archive.org/stream/centurydictionar12whituoft#page/n7/mode/2up">M - Zythiaceæ</a></li>
</ul>

<p class="sub-title">
  Consult also the <a class="internal" href="century-dictionary">Century dictionary</a>
</p>