<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">8 volumes - 7 000 pages - 260,000 entries</span>
</p>

<p>
The <a href="http://en.wikipedia.org/wiki/Century_Dictionary">Century Dictionary</a>
is “designed to be a practically complete record of the main body of English speech, from the time of the mingling of the Old French and
Anglo-Saxon to the present day”, including “technical terms of the various sciences, arts, trades, and professions”.
It offers “definitions proper of such related encyclopedic matter” with the addition of “pictorial illustrations”.
</p>

<p class="sub-title">Links to the books at <a href="http://archive.org/">archive.org</a></p>
<ul>
  <li>Volume 1: <a href="http://archive.org/stream/centurydict01whit#page/n7/mode/2up">A - Celticism</a></li>
  <li>Volume 2: <a href="http://archive.org/stream/cu31924091890594#page/n7/mode/2up">Celticize - Drool</a></li>
  <li>Volume 3: <a href="http://archive.org/stream/cu31924091890602#page/n7/mode/2up">Droop - Gyves</a></li>
  <li>Volume 4: <a href="http://archive.org/stream/cu31924091890610#page/n7/mode/2up">H - Lyverey</a></li>
  <li>Volume 5: <a href="http://archive.org/stream/cu31924091890628#page/n7/mode/2up">M - Pharmacolite</a></li>
  <li>Volume 6: <a href="http://archive.org/stream/cu31924091890636#page/n7/mode/2up">Pharmacological - Salse</a></li>
  <li>Volume 7: <a href="http://archive.org/stream/cu31924091890644#page/n7/mode/2up">Salsify - Technical</a></li>
  <li>Volume 8: <a href="http://archive.org/stream/cu31924091890651#page/n7/mode/2up">Technicality - Zyxomma</a></li>
</ul>

<p class="sub-title">
  Consult also the <a class="internal" href="century-supplement">Century dictionary supplement</a>
</p>