<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">10 volumes - 8 000 pages - 40,000 entries</span>
</p>

<p>
The <a href="http://en.wikipedia.org/wiki/Chambers's_Encyclopaedia">Chambers's Encyclopaedia</a>
is “a stocktaking in almost every department of science”.
It “strives to be at once comprehensive, compact, accurate, lucid, readable, and handy for reference”.
</p>

<p class="sub-title">Links to the books at <a href="http://archive.org/">archive.org</a></p>
<ul>
  <li>Volume 1:  <a href="https://archive.org/stream/chamberssency01lond#page/n5/mode/2up">A - Beaufort</a></li>
  <li>Volume 2:  <a href="https://archive.org/stream/chamberssency02lond#page/n3/mode/2up">Beaugency - Cataract</a></li>
  <li>Volume 3:  <a href="https://archive.org/stream/chamberssency03lond#page/n3/mode/2up">Catarrh - Dion</a></li>
  <li>Volume 4:  <a href="https://archive.org/stream/chamberssency04lond#page/n3/mode/2up">Dionysius - Friction</a></li>
  <li>Volume 5:  <a href="https://archive.org/stream/chamberssency05lond#page/n3/mode/2up">Friday - Humanitarians</a></li>
  <li>Volume 6:  <a href="https://archive.org/stream/chamberssency06lond#page/n3/mode/2up">Humber - Malta</a></li>
  <li>Volume 7:  <a href="https://archive.org/stream/chamberssency07lond#page/n3/mode/2up">Maltebrun - Peary</a></li>
  <li>Volume 8:  <a href="https://archive.org/stream/chamberssency08lond#page/n3/mode/2up">Peasant - Roumelia</a></li>
  <li>Volume 9:  <a href="https://archive.org/stream/chambersencyclop09lond#page/n3/mode/2up">Round - Swansea</a></li>
  <li>Volume 10: <a href="https://archive.org/stream/chambersencyclop10lond#page/n5/mode/2up">Swastika - Zyrianovsk</a></li>
</ul>
