<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">52 pages, 2 900 entrées en ligne</span>
</p>

<a href="http://fr.wikipedia.org/wiki/Le_Couronnement_de_Louis">La Couronnement de Louis</a>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce glossaire a été numérisé sous la direction de Hitoshi Ogurisu de l'université de Wakayama.</li>
  <li>Cette version numérique, réf. EGlos_CourLouisL1, a été gracieusement mise à la disposition de DicFro pour une utilisation dans le respect des droits suivants: « Le droit d'auteur du Glossaire du Couronnement de Louis est déjà expiré, et tous les travaux nécessaires (enregistrement des mots vedettes, scanning etc) sont tous exécutés par nous [H.O.]. Les droits provenant de cette version nous [H.O.] appartiennent complètement, et nous [H.O.] ne les exercerons jamais pourvu que vous en fassiez un emploi strictement personnel : ce dictionnaire électronique est/sera gratuit et disponible pour tous les particuliers ».</li>
  <li>Une version hors-ligne est aussi disponible.</li>
  <li>Ce glossaire utilise la liste de lemmes du Tobler-Lommatzsch pour identifier les mots.</li>
  <li>Ce glossaire utilise les tableaux de conjugaison de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
  <li>
    <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a>,
    <a href="http://www.eonet.ne.jp/~ogurisu/Fr/DicosSporadiques.html">Version hors ligne</a>,
    <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a>,
    <a href="tableaux-de-conjugaison">Tableaux de conjugaison</a>
  </li>
</ul>