<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">20 volumes, 12 000 pages, 8 000 entrées</span>
</p>

Voir aussi <a href="http://fr.wikipedia.org/wiki/Grand_Larousse_encyclop%C3%A9dique">le Grand Larousse encyclopédique</a>

<p class="sub-title">Liens vers les volumes sur  <a href="http://gallica.bnf.fr/">gallica.bnf.fr</a></p>
<ul>
  <li>Volume 1  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200512k/f1.image">Aalto - amidon</a></li>
  <li>Volume 2  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005130/f1.image">Amiens - Austen</a></li>
  <li>Volume 3  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200514d/f1.image">Australie - bouddhisme</a></li>
  <li>Volume 4  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200515t/f1.image">Boudin - cestodes</a></li>
  <li>Volume 5  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005167/f1.image">Cétacés - composition</a></li>
  <li>Volume 6  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200517n/f1.image">Compresseur - design</a></li>
  <li>Volume 7  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005182/f1.image">Désinfection - épigraphie</a></li>
  <li>Volume 8  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200519g/f1.image">Épilepsie - français</a></li>
  <li>Volume 9  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005204/f1.image">France - Guesclin</a></li>
  <li>Volume 10 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200521j/f1.image">Guesde - Ingres</a></li>
  <li>Volume 11 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200522z/f1.image">Initiation - Laos</a></li>
  <li>Volume 12 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200523c/f1.image">La Pérouse - Marches</a></li>
  <li>Volume 13 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200524s/f1.image">Marconi - mouvement</a></li>
  <li>Volume 14 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005256/f1.image">Moyen âge - Ostie</a></li>
  <li>Volume 15 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200526m/f1.image">Ostrava - pliage</a></li>
  <li>Volume 16 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005271/f1.image">Plomb - Renaissance</a></li>
  <li>Volume 17 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200528f/f1.image">Renan - science</a></li>
  <li>Volume 18 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200529v/f1.image">Science - fiction - syndicat</a></li>
  <li>Volume 19 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200530h/f1.image">Syndrome - Turquie</a></li>
  <li>Volume 20 : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200531x/f1.image">Tuyau - Zwingli</a></li>
</ul>

<p class="sub-title">
  <span class="middle">Attention ! Indexation en cours, volumes 1-3 (30%) indexés au 3/5/2013</span>
</p>