<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2015 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">2 volumes, 2300 pages, 75 000 entrées</span>
</p>

<a href="http://fr.wikipedia.org/wiki/Lou_Tresor_d%C3%B3u_Felibrige">Lou Tresor dóu Felibrige</a>
ou «&nbsp;Dictionnaire provençal-français&nbsp;: embrassant les divers dialectes de la langue d'oc moderne&nbsp;»,
composé par l'écrivain provençal de langue d'oc
<a href="http://fr.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Mistral">Frédéric Mistral</a>.

<p class="sub-title">Pages notables</p>
<ul>
  <li><a href="http://gallica.bnf.fr/ark:/12148/bpt6k74854/f1.highres">Titre</a></li>
  <li><a href="http://gallica.bnf.fr/ark:/12148/bpt6k74854/f4.highres">Avant-propos</a></li>
  <li><a href="http://gallica.bnf.fr/ark:/12148/bpt6k74854/f5.highres">Au miejour</a></li>
  <li><a href="http://gallica.bnf.fr/ark:/12148/bpt6k74854/f6.highres">Abréviations</a></li>
  <li><a href="http://gallica.bnf.fr/ark:/12148/bpt6k74854/f7.highres">Avertissement</a></li>
</ul>

<p class="sub-title">Liens vers les volumes sur <a href="http://archive.org/">archive.org</a></p>
<ul>
  <li>Tome 1 : <a href="https://archive.org/stream/loutrsordufelibr01mist#page/n9/mode/2up">A - F</a></li>
  <li>Tome 2 : <a href="https://archive.org/stream/loutrsordufelibr02mist#page/n7/mode/2up">G - Z</a></li>
</ul>
