<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">1 700 pages, 60 000 entrées</span>
</p>

<p>« Le dictionnaire de Félix <a href="http://fr.wikipedia.org/wiki/Gaffiot">Félix Gaffiot</a> embrasse toute la latinité, de la Loi des Douzes Tables aux auteurs du Digeste », « avec un effort particulier pour la période de Plaute à Tacite ». « Les formes archaïques et les formes vulgaires » sont mentionnées. « Le sens général des mots, les sens
  particuliers sont éclairés par de nombreux exemples ou appuyés par des renvois aux auteurs ».</p>

<p class="sub-title">Pages notables</p>
<ul>
  <li><a href="<?=$this->setLinkUrl('dictionary/gaffiot/mImg/ex/ex0001.gif');?>">Titre</a></li>
  <li><a href="<?=$this->setLinkUrl('dictionary/gaffiot/mImg/ex/ex0006.gif');?>">Préface</a></li>
  <li><a href="<?=$this->setLinkUrl('dictionary/gaffiot/mImg/ex/ex0007.gif');?>">Avant-propos</a></li>
</ul>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce dictionnaire a été numérisé sous la direction de <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a> de l'université de Wakayama.</li>
  <li>Cette version numérique, réf. GaffiotEdic, a été gracieusement mise à la disposition de DicFro pour une utilisation dans le respect des droits suivants: « Le droit d'auteur de Gaffiot est déjà expiré, et tous les travaux nécessaires (enregistrement des mots vedettes, scanning etc) sont tous exécutés par nous [H.O.]. Les droits provenant de cette version nous [H.O.] appartiennent complètement, et nous [H.O.] ne les exercerons jamais pourvu que vous en fassiez un emploi strictement personnel : ce dictionnaire électronique est/sera gratuit et disponible pour tous les particuliers ».</li>
  <li>Une <a href="http://www.eonet.ne.jp/~ogurisu/Fr/Gaffiot.html">version hors ligne</a> est aussi disponible.</li>
  <li>Ce dictionnnaire utilise la liste de mots du <a href="http://users.erols.com/whitaker/dictpage.htm">Whitaker</a> pour identifier les mots recherchés.</li>
</ul>