<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">10 volumes, 8 000 pages, 160 000 entrées</span>
</p>

<p>Le dictionnaire d'ancien français de <a href="http://fr.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Godefroy">Frédéric Godefroy</a> contient « les mots de la langue du moyen âge que la langue moderne n'a pas gardés ». Certains mots ont été conservés, « pour certaines significations disparues ». « Chaque forme de mot, chaque signification et chaque nuance de sens » sont justifiés « par des exemples abondants et variés, empruntés aux manuscrits les plus authentiques des diverses bibliothèques et archives ». Les mots référencés sont principalement ceux « consacrés par les meilleurs écrivains, poètes et prosateurs, des XIème, XIIème et XIIIème siècles ».</p>

<p class="sub-title">Pages notables</p>
<ul>
  <li>Tome 1 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc01/01etc002.gif');?>">titre</a>, avertissement
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc01/01etc005.gif');?>">p.1</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc01/01etc006.gif');?>">p.2</a>
  </li>
  <li>Tome 2 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc02/02etc003.gif');?>">titre</a>, avertissement
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc02/02etc005.gif');?>">p.1</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc02/02etc006.gif');?>">p.2</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc02/02etc007.gif');?>">p.3</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc02/02etc008.gif');?>">p.4</a>
  </li>
  <li>Tome 3 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc03/03etc003.gif');?>">titre</a>
  </li>
  <li>Tome 4 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc04/04etc003.gif');?>">titre</a>
  </li>
  <li>Tome 5 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc05/05etc003.gif');?>">titre</a>, avertissement
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc05/05etc005.gif');?>">p.1</a>
  </li>
  <li>Tome 6 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc003.gif');?>">titre</a>, préface
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc005.gif');?>">p.1</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc006.gif');?>">p.2</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc007.gif');?>">p.3</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc008.gif');?>">p.4</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc009.gif');?>">p.5</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc010.gif');?>">p.6</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc011.gif');?>">p.7</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc012.gif');?>">p.8</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc013.gif');?>">p.9</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc014.gif');?>">p.10</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc015.gif');?>">p.11</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc016.gif');?>">p.12</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc017.gif');?>">p.13</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc018.gif');?>">p.14</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc06/06etc019.gif');?>">p.15</a>
  </li>
  <li>Tome 7 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc07/07etc003.gif');?>">titre</a>, avertissement
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc07/07etc005.gif');?>">p.1</a>,
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc07/07etc006.gif');?>">p.2</a>
  </li>
  <li>Tome 8 :
    <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc08/08etc003.gif');?>">titre</a>
  </li>
</ul>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce dictionnaire a été numérisé sous la direction de <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a> de l'université de Wakayama.</li>
  <li>Cette version numérique, réf. GdfEdic, a été gracieusement mise à la disposition de DicFro pour une utilisation dans le respect des droits suivants: « Le droit d'auteur de Godefroy est déjà expiré, et tous les travaux nécessaires (enregistrement des mots vedettes, scanning etc) sont tous exécutés par nous [H.O.]. Les droits provenant de cette version nous [H.O.] appartiennent complètement, et nous [H.O.] ne les exercerons jamais pourvu que vous en fassiez un emploi strictement personnel : ce dictionnaire électronique est/sera gratuit et disponible pour tous les particuliers ».</li>
  <li>Une <a href="http://www.eonet.ne.jp/~ogurisu/Fr/Godefroy.html">version hors ligne</a> est aussi disponible.</li>
  <li>Ce dictionnaire utilise la base des <a href="http://atilf.atilf.fr/gsouvay/scripts/fantomes.exe">mots fantômes</a> de l'Atilf. Cette base recense « les pseudo-lexèmes disposant à tort d'un statut lexicographique, les sens fantômes ainsi que les lemmatisations erronées ».</li>
  <li>Ce dictionnnaire utilise la liste de lemmes du <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a> pour identifier les mots.</li>
  <li>Ce dictionnnaire utilise les <a href="tableaux-de-conjugaison">tableaux de conjugaison</a> de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
</ul>

<p class="sub-title">
  Consultez aussi le <a href="complement-godefroy">complément</a> du dictionnaire
  et le <a class="internal" href="lexique-godefroy">lexique</a>
</p>