<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p>Le complément du dictionnaire de <a href="http://fr.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Godefroy">Frédéric Godefroy</a> contient des mots et des définitions supplémentaires.</p>

<p class="sub-title">Pages notables</p>
<ul>
  <li>Tome 8 :
      <a href="<?=$this->setLinkUrl('dictionary/gdf/mImg/etc08/08etc003.gif');?>">titre</a>, avertissement
      <a href="<?=$this->setLinkUrl('dictionary/gdfc/mImg/GdfC8etc/0810005.gif');?>">p.1</a>,
      <a href="<?=$this->setLinkUrl('dictionary/gdfc/mImg/GdfC8etc/0810006.gif');?>">p.2</a>,
      <a href="<?=$this->setLinkUrl('dictionary/gdfc/mImg/GdfC8etc/0810007.gif');?>">p.3</a>
  </li>
  <li>Tome 9 :
      <a href="<?=$this->setLinkUrl('dictionary/gdfc/mImg/GdfC9etc/0003.gif');?>">titre</a>, avertissement
      <a href="<?=$this->setLinkUrl('dictionary/gdfc/mImg/GdfC9etc/0005.gif');?>">p.1</a>
  </li>
  <li>Tome 10 :
      <a href="<?=$this->setLinkUrl('dictionary/gdfc/mImg/etc_10/1010880.gif');?>">titre</a></li>
</ul>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce dictionnaire a été numérisé sous la direction de <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a> de l'université de Wakayama.</li>
  <li>Cette version numérique, réf. GdfCEdic, a été gracieusement mise à la disposition de DicFro pour une utilisation dans le respect des droits suivants: « Le droit d'auteur de Godefroy est déjà expiré, et tous les travaux nécessaires (enregistrement des mots vedettes, scanning etc) sont tous exécutés par nous [H.O.]. Les droits provenant de cette version nous [H.O.] appartiennent complètement, et nous [H.O.] ne les exercerons jamais pourvu que vous en fassiez un emploi strictement personnel : ce dictionnaire électronique est/sera gratuit et disponible pour tous les particuliers ».</li>
  <li>Une <a href="http://www.eonet.ne.jp/~ogurisu/Fr/Godefroy.html">version hors ligne</a> est aussi disponible.</li>
  <li>Ce dictionnaire utilise la base des <a href="http://atilf.atilf.fr/gsouvay/scripts/fantomes.exe">mots fantômes</a> de l'Atilf. Cette base recense « les pseudo-lexèmes disposant à tort d'un statut lexicographique, les sens fantômes ainsi que les lemmatisations erronées ».</li>
  <li>Ce dictionnnaire utilise la liste de lemmes du <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a> pour identifier les mots.</li>
  <li>Ce dictionnnaire utilise les <a href="tableaux-de-conjugaison">tableaux de conjugaison</a> de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
</ul>

<p class="sub-title">
  Consultez aussi le <a class="internal" href="dictionnaire-godefroy">dictionnaire</a>
  et le <a class="internal" href="lexique-godefroy">lexique</a>
</p>