<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">550 pages, 55 000 entrées</span>
</p>

<p>Le lexique d'ancien français de <a href="http://fr.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Godefroy">Frédéric Godefroy</a> complète le dictionnaire de plusieurs centaines d'entrées. Il couvre l'ensemble de l'ancienne langue française du IXe au XVe siècle. Chaque mot est accompagné de sa classe grammaticale, de sa traduction ainsi que de divers sens.</p>

<p class="sub-title">Pages notables</p>
<ul>
  <li><a href="<?=$this->setLinkUrl('dictionary/gdflex/mImg/0000547.gif');?>">Titre</a></li>
  <li><a href="<?=$this->setLinkUrl('dictionary/gdflex/mImg/0000549.gif');?>">Avis</a></li>
</ul>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce dictionnaire a été numérisé sous la direction de <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a> de l'université de Wakayama.</li>
  <li>Cette version numérique, réf. GdfLexEdic, a été gracieusement mise à la disposition de DicFro pour une utilisation dans le respect des droits suivants: « Le droit d'auteur de Godefroy est déjà expiré, et tous les travaux nécessaires (enregistrement des mots vedettes, scanning etc) sont tous exécutés par nous [H.O.]. Les droits provenant de cette version nous [H.O.] appartiennent complètement, et nous [H.O.] ne les exercerons jamais pourvu que vous en fassiez un emploi strictement personnel : ce dictionnaire électronique est/sera gratuit et disponible pour tous les particuliers ».</li>
  <li>Une <a href="http://www.eonet.ne.jp/~ogurisu/Fr/Godefroy.html">version hors ligne</a> est aussi disponible.</li>
  <li>Ce dictionnaire utilise la base des <a href="http://atilf.atilf.fr/gsouvay/scripts/fantomes.exe">mots fantômes</a> de l'Atilf. Cette base recense « les pseudo-lexèmes disposant à tort d'un statut lexicographique, les sens fantômes ainsi que les lemmatisations erronées ».</li>
  <li>Ce dictionnnaire utilise la liste de lemmes du <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a> pour identifier les mots.</li>
  <li>Ce dictionnnaire utilise les <a href="tableaux-de-conjugaison">tableaux de conjugaison</a> de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
</ul>

<p class="sub-title">
  Consultez aussi le <a href="dictionnaire-godefroy">dictionnaire</a> et
  le <a href="complement-godefroy">complément</a> du dictionnaire
</p>