<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">7 volumes, 6 500 pages, 60 000 entrées</span>
</p>

<p>
Le Grand Larousse «&nbsp;offre un instrument de connaissance du lexique de notre langue&nbsp;»,
il concerne «&nbsp;tous les aspects de la langue, et rien que la langue&nbsp;».
Il propose «&nbsp;des informations de grammaire et de linguistique&nbsp» complètes,
afin de «&nbsp;parfaire les connaissances de l'homme cultivé&nbsp;» sur sa langue et son histoire.
</p>

Voir aussi <a href="http://fr.wikipedia.org/wiki/Grand_Larousse_encyclop%C3%A9dique">le Grand Larousse encyclopédique</a>

<p class="sub-title">Liens vers les volumes sur  <a href="http://gallica.bnf.fr/">gallica.bnf.fr</a></p>
<ul>
  <li>Tome 1  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200532b/f1.image">a - cippe</a></li>
  <li>Tome 2  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200533r/f1.image">cirage - érythrose</a></li>
  <li>Tome 3  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005345/f1.image">ès - incuse</a></li>
  <li>Tome 4  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200535k/f1.image">indatable - nystagmus</a></li>
  <li>Tome 5  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200551p/f1.image">o - psittacus</a></li>
  <li>Tome 6  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k1200556r/f1.image">psoas - survolteur</a></li>
  <li>Tome 7  : <a href="http://gallica.bnf.fr/ark:/12148/bpt6k12005590/f1.image">sus - zythum</a></li>
</ul>