<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">4 volumes, 1 100 pages, 50 000 entrées</span>
</p>

<a href="http://fr.wikipedia.org/wiki/Le_Petit_Larousse">Le Petit Larousse</a>

<p class="sub-title">Liens vers les volumes sur <a href="http://archive.org/">archive.org</a></p>
<ul>
  <li>Tome 1 : <a href="http://archive.org/stream/PetitLarousse19061/larousse_petit_1906_a#page/n7/mode/2up">A - C</a></li>
  <li>Tome 2 : <a href="http://archive.org/stream/PetitLarousse19062/larousse_petit_1906_b#page/n0/mode/2up">D - K</a></li>
  <li>Tome 3 : <a href="http://archive.org/stream/PetitLarousse19063/larousse_petit_1906_c#page/n0/mode/2up">L - Q</a></li>
  <li>Tome 4 : <a href="http://archive.org/stream/PetitLarousse19064/larousse_petit_1906_d#page/n0/mode/2up">R - Z</a></li>
</ul>

<p class="sub-title">
  Consultez aussi le dictionnaire des <a href="petit-larousse-np">noms propres</a>
</p>