<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">2 volumes, 600 pages, 25 000 entrées</span>
</p>

<a href="http://fr.wikipedia.org/wiki/Le_Petit_Larousse">Le Petit Larousse</a>

<p class="sub-title">Liens vers les volumes sur <a href="http://archive.org/">archive.org</a></p>
<ul>
  <li>Tome 5 : <a href="http://archive.org/stream/PetitLarousse19065/larousse_petit_1906_e#page/n0/mode/2up">A - J</a></li>
  <li>Tome 6 : <a href="http://archive.org/stream/PetitLarousse19066/larousse_petit_1906_f#page/n0/mode/2up">K - Z</a></li>
</ul>

<p class="sub-title">
  Consultez aussi le dictionnaire des <a href="petit-larousse">noms communs</a>
</p>