<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">55 pages, 2 400 entrées en ligne</span>
</p>

<a href="http://fr.wikipedia.org/wiki/Roman_de_Renart">Le Roman de Renart</a>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce glossaire a été extrait de la version PDF du Roman de Renart, volume 3, M. D. M. Méon, Treuttel et Würtz, Paris, 1826.</li>
  <li>Ce glossaire utilise la liste de lemmes du Tobler-Lommatzsch pour identifier les mots.</li>
  <li>Ce glossaire utilise les tableaux de conjugaison de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
  <li>
    <a href="http://books.google.fr/books?id=OpgCAAAAYAAJ&hl=fr&pg=PA385#v=onepage&f=false">Glossaire</a>,
    <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a>,
    <a href="tableaux-de-conjugaison">Tableaux de conjugaison</a>.
  </li>
</ul>

Voir aussi les glossaires des volumes
<a href="glossaire-roman-de-renart-meon-vol1">1</a>,
<a href="glossaire-roman-de-renart-meon-vol2">2</a>,
et
<a href="glossaire-roman-de-renart-meon-vol4">4</a>.