<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">44 pages, 1 900 entrées en ligne</span>
</p>

<a href="http://fr.wikipedia.org/wiki/Roman_de_Renart">Le Roman de Renart</a>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce glossaire est extrait de la version PDF du Roman de Renart, <a href="http://books.google.fr/books?id=WR72lYfyTP8C&hl=fr&pg=PA359#v=onepage&q&f=false">volume 1</a>, M. D. M. Méon, Treuttel et Würtz, Paris, 1826.</li>
  <li>Ce glossaire utilise la liste de lemmes du <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a> pour identifier les mots.</li>
  <li>Ce glossaire utilise les <a href="tableaux-de-conjugaison">tableaux de conjugaison</a> de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
</ul>

<p class="sub-title">
  Voir aussi les glossaires des volumes
  <a class="internal" href="glossaire-roman-de-renart-meon-vol2">2</a>,
  <a class="internal" href="glossaire-roman-de-renart-meon-vol3">3</a>,
  et
  <a class="internal" href="glossaire-roman-de-renart-meon-vol4">4</a>.
</p>