<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">28 pages, 1 500 entrées</span>
</p>

<a href="http://fr.wikipedia.org/wiki/Roman_de_Renart">Le Roman de Renart</a>
<br/>
<a href="http://roman-de-renart.blogspot.com/">Édition en français moderne et ancien</a>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce glossaire est extrait du Roman de Renart d'après les manuscrits C et M,
      N. Fukumoto, N. Harano et S. Suzuki, France Tosho, 1985.
  <li>Ce glossaire utilise la liste de lemmes du <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a> pour identifier les mots.</li>
  <li>Ce glossaire utilise les <a href="tableaux-de-conjugaison">tableaux de conjugaison</a> de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
</ul>