<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">260 verbes, 2 600 tables de conjugaison en ligne</span>
</p>

<p>Dans ce « recueil de formes verbales de l'ancien français, la plupart des formes recueillies et retenues sont des formes qui ont réellement existé, mais les formes qui peuvent sembler imaginaires ou fabriquées ne sont pourtant pas systématiquement écartées. »</p>

<p class="sub-title">Ressources</p>
<ul>
  <li>Cette version numérique, réf. Tcaf, a été gracieusement mise à la disposition de DicFro par Hitoshi Ogurisu de l'université de Wakayama, pour une utilisation dans le respect des droits suivants: « Nous [H.O.] n'avons pas abandonné le droit d'auteur qui nous [H.O.] revient de TCAF. Mais nous [H.O.] ne vous demanderons rien dans la mesure où vous l'utilisez personnellement. »</li>
  <li>Une version hors-ligne est aussi disponible.</li>
  <li>
    <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a>,
    <a href="http://www.eonet.ne.jp/~ogurisu/Fr/TCAF.html">Version hors ligne</a>
  </li>
</ul>