<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">101 pages, 2 500 entrées</span>
</p>

<a href="http://fr.wikipedia.org/wiki/B%C3%A9roul">Béroul</a>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce glossaire a été numérisé sous la direction de <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a> de l'université de Wakayama.</li>
  <li>Cette version numérique, réf. EGlos_TristBerM1, a été gracieusement mise à la disposition de DicFro pour une utilisation dans le respect des droits suivants: « Le droit d'auteur du Glossaire du Roman de Tristan est déjà expiré, et tous les travaux nécessaires (enregistrement des mots vedettes, scanning etc) sont tous exécutés par nous [H.O.]. Les droits provenant de cette version nous [H.O.] appartiennent complètement, et nous [H.O.] ne les exercerons jamais pourvu que vous en fassiez un emploi strictement personnel : ce dictionnaire électronique est/sera gratuit et disponible pour tous les particuliers ».</li>
  <li>Une <a href="http://www.eonet.ne.jp/~ogurisu/Fr/DicosSporadiques.html">version hors ligne</a> est aussi disponible.</li>
  <li>Ce glossaire utilise la liste de lemmes du <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a> pour identifier les mots.</li>
  <li>Ce glossaire utilise les <a href="tableaux-de-conjugaison">tableaux de conjugaison</a> de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
</ul>