<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Introduction
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<p class="sub-title">
  <span class="middle">536 pages, 17 500 entrées</span>
</p>

<p>Ce petit dictionnaire propose une « étude approfondie de l'étymologie », « un exposé de toutes les formes de déclinaisons et de conjugaison », « des variantes dialectiques ou orthographiques », et de nombreuses locutions et expressions.</p>

<p class="sub-title">Pages notables</p>
<ul>
  <li><a href="<?=$this->setLinkUrl('dictionary/vandaele-dictionary/mImg/0000003.gif');?>">Titre</a></li>
  <li>Avant-propos <a href="<?=$this->setLinkUrl('dictionary/vandaele-dictionary/mImg/0000005.gif');?>">p.1</a>,
    <a href="<?=$this->setLinkUrl('dictionary/vandaele-dictionary/mImg/0000006.gif');?>">p.2</a></li>
  <li><a href="<?=$this->setLinkUrl('dictionary/vandaele-dictionary/mImg/0000007.gif');?>">Étymologie</a></li>
  <li><a href="<?=$this->setLinkUrl('dictionary/vandaele-dictionary/mImg/0000008.gif');?>">Abréviations</a></li>
</ul>

<p class="sub-title">Ressources</p>
<ul>
  <li>Ce dictionnaire a été numérisé sous la direction de <a href="http://www.eonet.ne.jp/~ogurisu/">Hitoshi Ogurisu</a> de l'université de Wakayama.</li>
  <li>Cette version numérique, réf. Vandaele, a été gracieusement mise à la disposition de DicFro pour une utilisation dans le respect des droits suivants: « Le droit d'auteur de Van Daele est vraisemblablement expiré (à confirmer), et tous les travaux nécessaires (enregistrement des mots vedettes, scanning etc) sont tous exécutés par nous [H.O.]. Les droits provenant de cette version nous [H.O.] appartiennent complètement, et nous [H.O.] ne les exercerons jamais pourvu que vous en fassiez un emploi strictement personnel : ce dictionnaire électronique est/sera gratuit et disponible pour tous les particuliers ».</li>
  <li>Une <a href="http://www.eonet.ne.jp/~ogurisu/Fr/VanDaele.html">version hors ligne</a> est aussi disponible.</li>
  <li>Ce dictionnaire utilise la base des <a href="http://atilf.atilf.fr/gsouvay/scripts/fantomes.exe">mots fantômes</a> de l'Atilf. Cette base recense « les pseudo-lexèmes disposant à tort d'un statut lexicographique, les sens fantômes ainsi que les lemmatisations erronées ».</li>
  <li>Ce dictionnnaire utilise la liste de lemmes du <a href="http://www.uni-stuttgart.de/lingrom/stein/tl/downloadsf.htm">Tobler-Lommatzsch</a> pour identifier les mots.</li>
  <li>Ce dictionnnaire utilise les <a href="tableaux-de-conjugaison">tableaux de conjugaison</a> de l'ancien français de Machio Okada et Hitoshi Ogurisu pour identifier les verbes.</li>
</ul>