<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title">À propos</h1>

<p class="sub-title">
  <span class="middle">Pourquoi DicFro ?</span>
</p>

<ul>
  <li>DicFro = Dic + Fro. [Dic] vient du mot dictionnaire. [Fro] est le code ISO de l'ancien français.</li>
  <li>En 2007, il n'y avait pas de dictionnaire d'ancien français en ligne sur Internet.
      Il existait une  solution intéressante hors ligne réalisée par Hitoshi Ogurisu, qui d'ailleurs est toujours disponible.
      L'idée était d'offrir une interface web simple pour rechercher un mot dans ce dictionnaire.
      D'autres dictionnaires ont été ajoutés par la suite.
  </li>
</ul>

<a href="http://code.google.com/p/dicfro/source/list">Journal des modifications</a>
<br/>
<a href="http://my.statcounter.com/project/standard/stats.php?project_id=5407064&guest=1">Statistiques</a>
<br/>
<a class="link" href="<?=$this->setActionUrl('archives');?>">Archives</a>