<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title"><?=$this->translate('About');?></h1>

<a href="http://code.google.com/p/dicfro/source/list"><?=$this->translate('Change log');?></a>
<?=$this->translate('(in English)', '');?>
<br/>
<a href="http://my.statcounter.com/project/standard/stats.php?project_id=5407064&guest=1"><?=$this->translate('Statistics');?></a>
<?=$this->translate('(in English)', '');?>
<br/>
<a href="<?=$this->setActionUrl('archives');?>"><?=$this->translate('Archives');?></a>
<?=$this->translate('(in French)');?>