<ul>
  <li>Les flèches vertes permettent de feuilleter un dictionnaire de type papier.</li>
  <li>
      Dans le cas d'un dictionnaire numérisé,
      le premier mot de la page, le numéro de la page, et le numéro de volume sont affichés en haut à droite.<br />
      Vous pouvez aller directement à une page donnée dans un volume donné.
  </li>
  <li>
      Un dictionnaire peut être ouvert dans l'onglet courant ou dans un onglet différent.
      <a href="<?=$this->setActionUrl($this->optionsLink);?>">Changer le mode d'ouverture d'un dictionnaire.</a>
  </li>
  <li>
      Un mot peut être recherché automatiquement quand on passe d'un dictionnaire à un autre,
      lorsqu'ils sont ouverts dans des onglets différents.
      <a href="<?=$this->setActionUrl($this->optionsLink);?>">Changer le mode de recherche d'un mot.</a>
  </li>
</ul>
