<ol>
  <li>Tapez un mot dans la boîte verte, et cliquez sur le bouton vert.</li>
  <li>La page contenant le mot, s'affiche immédiatement.
      Dans le cas d'un dictionnaire numérisé,
      cherchez alors ce mot dans la page, comme dans un dictionnaire papier.
      Notez que ce mot n'existe peut-être pas dans ce dictionnaire.</li>
  <li>Pour sélectionner un autre dictionnaire, cliquez dans la liste déroulante à droite du bouton vert.
      La recherche du mot est effectuée automatiquement, et la page correspondante de ce dictionnaire s'affiche aussitôt.
      DicFro utilise le dictionnaire Godefroy par défaut.</li>
</ol>
