<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2015 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title"><?=$this->translate('Dictionaries page test');?></h1>

<table class="test-result">

<?php foreach($this->results as $results):?>

  <?php if (! empty($results['result'])):?>
    <tr>

    <?php foreach($results['result'] as $index => $result):?>

      <td class="nowrap">
        <?php if (count($results['result']) > 1):?>
          <?=$results['name'];?> #<?=$index + 1;?>
        <?php else:?>
          <?=$results['name'];?>
        <?php endif;?>
      </td>

      <td class="nowrap"><?=implode('/', $result['page']);?></td>

      <?php if (! $result):?>
        <td class="orange nowrap">Not tested</td>

      <?php elseif (! isset($results['expected']) or ! isset($results['expected'][$index])):?>
        <td class="orange nowrap">Need validation!</td>
        <td class="nowrap"><a href="javascript:hideOrDisplay('<?=$results['id'];?>-<?=$index;?>')">See details</a></td>
        <td>
          <span class="orange">Please check the result and keep or remove tests/page/<?=$results['id'];?> accordingly</span>
          <pre class="test-result" id="<?=$results['id'];?>-<?=$index;?>">
Test result
<?=preg_replace('~^Array\n\(\n(.+?)\n\)\n$~is', '$1', print_r($result, true));?>
          </pre>
        </td>

      <?php elseif ($result == $results['expected'][$index]):?>
        <td class="green nowrap">Test OK</td>
        <td class="nowrap"><a href="javascript:hideOrDisplay('<?=$results['id'];?>-<?=$index;?>')">See details</a></td>
        <td>
            <pre class="test-result" id="<?=$results['id'];?>-<?=$index;?>">
Test result = Expected result
<?=preg_replace('~^Array\n\(\n(.+?)\n\)\n$~is', '$1', print_r($result, true));?>
            </pre>
        </td>

      <?php else:?>
        <td class="nowrap red">Error!</td>
        <td class="nowrap"><a href="javascript:hideOrDisplay('<?=$results['id'];?>-<?=$index;?>')">See details</a></td>
        <td>
          <span class="red">Fix or remove &quot;tests/page/<?=$results['id'];?>&quot; accordingly</span>
          <pre class="test-result" id="<?=$results['id'];?>-<?=$index;?>">
Test result:
<?=preg_replace('~^Array\n\(\n(.+?)\n\)\n$~is', '$1', print_r($result, true));?>

Expected result:
<?=preg_replace('~^Array\n\(\n(.+?)\n\)\n$~is', '$1', print_r($results['expected'][$index], true));?>
          </pre>
        </td>

      <?php endif;?>
    </tr>

    <?php endforeach;?>

  <?php else:?>
    <tr>
      <td class="nowrap"><?=$results['name'];?></td>
      <td></td>
      <td><span class="orange nowrap">Not tested!</span></td>
    </tr>
  <?php endif;?>

<?php endforeach;?>

</table>
