<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title">Liste des dictionnaires</h1>

  (dictionnaire
  <a class="internal">interne</a> à DicFro en vert,
  <a class="index">indexé</a> dans DicFro en bleu,
  <a class="external">externe</a> à DicFro en noir)


<?php foreach($this->dictionariesHelper->getGroups() as $optgroup) :?>
  <p class="sub-title"><?=$optgroup['label'];?></p>

    <ul>
    <?php foreach($optgroup['options'] as $options) :?>

      <li>
      <a class="link <?=$options['type'];?>"
         href="<?=$this->setActionUrl('introduction/' . $options['value']);?>"><?=$options['title'];?></a>
      </li>

    <?php endforeach;?>
    </ul>

<?php endforeach;?>
