<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title">Liste des dictionnaires</h1>

<?php foreach($this->dictionariesHelper->getGroups() as $optgroup) :?>
  <p class="sub-title"><?=$optgroup['label'];?></p>

    <ul>
    <?php foreach($optgroup['options'] as $options) :?>

      <li>
      <a class="link <?=$options['type'];?>"
         href="<?=$this->setActionUrl('introduction/' . $options['value']);?>"><?=$options['title'];?></a>
      </li>

    <?php endforeach;?>
    </ul>

<?php endforeach;?>

<p class="sub-title">DicFro propose 3 types de dictionnaire</p>
<ul>
  <li><a class="internal">Dictionnaire interne :</a> les pages du dictionnaire et l'index des pages sont stockés dans DicFro.</li>
  <li><a class="index">Dictionnaire indexé :</a> les pages du dictionnaire sont stockées hors de DicFro,
      l'index des pages est stocké dans DicFro. DicFro effectue la recherche d'un mot dans l'index,
      et affiche la page correspondante du dictionnaire, comme pour un dictionnaire interne.
  </li>
  <li><a class="external">Dictionnaire externe :</a> les pages du dictionnaire sont sockées hors de DicFro.
      DicFro passe le mot recherché au dictionnaire qui effectue la recherche et affiche la page du mot.
  </li>
</ul>
