<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title">Aide</h1>

<p class="sub-title">Utilisation de base</p>
<?php require "{$this->viewsDir}/information/basic-search.phtml";?>

<p class="sub-title">Utilisation avancée</p>
<?php require "{$this->viewsDir}/information/advanced-search.phtml";?>

<br />
<p>N'hésitez pas à nous contacter si vous rencontrez un problème ou si vous souhaitez faire un commentaire. Merci.</p>

<a class="translate" href="mailto:mcorne@yahoo.com?subject=Question%20sur%20Dicfro">Contactez nous</a>