<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title">Dictionnaires de français, latin et anglais</h1>

<p class="sub-title">3 raisons d'utiliser DicFro</p>

<ul>
  <li>
      Effectuer facilement des recherches dans des dictionnaires dont les pages ont été numérisées,
      comme dans un dictionnaire papier.
  </li>
  <li>Faire des recherches dans d'autres dictionnaires disponibles sur l'internet.</li>
  <li>
      Rechercher dans plusieurs dictionnaires en parallèle.
      <a href="<?=$this->setActionUrl($this->optionsLink);?>">Voir les options.</a>
  </li>
</ul>

<a href="<?=$this->setActionUrl($this->dictionariesLink);?>">Liste des dictionnaires</a>
