<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title">Dictionnaires de français, latin et anglais</h1>

<p class="sub-title">3 raisons d'utiliser DicFro</p>

<ul>
  <li>
      Effectuer facilement des recherches dans des dictionnaires dont les pages ont été numérisées,
      comme dans un dictionnaire papier.
  </li>
  <li>Faire des recherches dans d'autres dictionnaires disponibles sur l'internet.</li>
  <li>
      Rechercher dans plusieurs dictionnaires en parallèle.
      <a href="<?=$this->setActionUrl($this->optionsLink);?>">Voir les options</a>
  </li>
</ul>

<?php if ($newDictionaries = $this->dictionariesHelper->getNewDictionaries()):?>
  <p class="sub-title" title="Nouveautés des 30 derniers jours">
    <?php if (count($newDictionaries) == 1):?>
      Nouveau
   <?php else:?>
      Nouveautés
   <?php endif;?>
  </p>

  <ul>
    <?php foreach($newDictionaries as $option) :?>
      <li>
        <a class="link <?=$option['type'];?>"
           href="<?=$this->setActionUrl('introduction/' . $option['value']);?>"><?=$option['title'];?></a>
     </li>
    <?php endforeach;?>
  </ul>
<?php endif;?>

<a href="<?=$this->setActionUrl($this->dictionariesLink);?>">Liste de tous les dictionnaires</a>
