<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2013 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

?>

<h1 class="title"><?=$this->translate('French, English and Latin dictionaries');?></h1>

<p class="sub-title"><?=$this->translate('3 reasons to use DicFro');?></p>

<ul>
  <li><?=$this->translate('Easy search in dictionaries whose pages have been scanned, as in a paper dictionary');?></li>
  <li><?=$this->translate('Search in other dictionaries available on the internet');?></li>
  <li><?=$this->translate('Search in several dictionaries in parallel');?>
      <br/>
      <a href="<?=$this->setActionUrl($this->optionsLink);?>"><?=$this->translate('See the options');?></a>
  </li>
</ul>

<?php if ($newDictionaries = $this->dictionariesHelper->getNewDictionaries()):?>
  <p class="sub-title" title="<?=$this->translate('New additions of the last 30 days');?>">
    <?php if (count($newDictionaries) == 1):?>
      <?=$this->translate('Recently added dictionary');?>
   <?php else:?>
      <?=$this->translate('Recently added dictionaries');?>
   <?php endif;?>
  </p>

  <ul>
    <?php foreach($newDictionaries as $option) :?>
      <li>
        <a class="link <?=$option['type'];?>"
           href="<?=$this->setActionUrl('introduction/' . $option['value']);?>"><?=$option['title'];?></a>
     </li>
    <?php endforeach;?>
  </ul>
<?php endif;?>

<a href="<?=$this->setActionUrl($this->dictionariesLink);?>"><?=$this->translate('List of all dictionaries');?></a>