<?php

/**
 * Dicfro
 *
 * PHP 5
 *
 * @category   DicFro
 * @package    View
 * @subpackage Scripts_Information
 * @author     Michel Corne <mcorne@yahoo.com>
 * @copyright  2008-2010 Michel Corne
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1 class="title"><?=$this->translate('Options');?></h1>

<p class="sub-title"><?=$this->translate('How to open a dictionary');?></p>

<table class="options">
  <tr>
    <td>
      <input type="radio" name="open-dictionary" value=""
             <?php if($this->isIE):?>class="ie"<?php endif;?>
             <?php if(!$this->newTab):?>checked="checked"<?php endif;?>
             onclick="unsetNewTab()"/>
    </td>
    <td class="text"><?=$this->translate('The selection of a new dictionary will open the dictionary in the current tab.');?></td>
  </tr>
  <tr>
    <td>
      <input type="radio" name="open-dictionary" value="1"
             <?php if($this->isIE):?>class="ie"<?php endif;?>
             <?php if($this->newTab):?>checked="checked"<?php endif;?>
             onclick="setNewTab()"/>
    </td>
    <td class="text">
      <?=$this->translate('The selection of a new dictionary will open the dictionary in a new tab.');?><br />
      <b><?=$this->translate('The opening of dictionaries in different tabs allows you to search in parallel.');?></b><br />
      <?=$this->translate('Warning! If your browser blocks pop-ups, please change the setting to always allow pop-ups for this site.');?>
    </td>
  </tr>
</table>

<p class="sub-title"><?=$this->translate('How to search a word');?></p>

<p><?=$this->translate('Applicable for dictionaries open in different tabs');?></p>

<table class="options">
  <tr>
    <td>
      <input type="radio" name="word-auto-search" value=""
             <?php if($this->isIE):?>class="ie"<?php endif;?>
             <?php if($this->autoSearch):?>checked="checked"<?php endif;?>
             onclick="setAutoSearch()"/>
    </td>
    <td>
      <?=$this->translate('The last searched word in a dictionary of a language will be searched automatically when switching from one tab to another.');?>
    </td>
  </tr>
  <tr>
    <td>
      <input type="radio" name="word-auto-search" value=""
             <?php if($this->isIE):?>class="ie"<?php endif;?>
             <?php if(!$this->autoSearch):?>checked="checked"<?php endif;?>
             onclick="unsetAutoSearch()"/>
    </td>
    <td><?=$this->translate('The automatic search of a word is disabled.');?></td>
  </tr>
</table>

<p class="sub-title"><?=$this->translate('Language of the user interface');?></p>

<div>
  <select class="language" id="language">
    <?php foreach ($this->languages as $code => $language):?>
      <?php if (empty($language['no-ui'])):?>
        <option value="<?=$code;?>"
                title="<?=$language['english'];?>"
                <?php if ($code == $this->language): ?>selected="selected"<?php endif;?>>
          <?=$language['original'];?>
        </option>
      <?php endif;?>
    <?php endforeach;?>
  </select>

  <input class="button" type="button"
         onclick="changeLanguage()"
         value="<?=$this->translate('Change');?>" />
</div>
